Update some commands, mostly networking
rtorrent-community/rtorrent-docs pull request #1
Opened 2017-03-25 17:21 UTC by kannibalox

2017-03-25 22:08 UTC, pyroscope requested changes
some fixes needed.

2017-03-25 22:08 UTC, pyroscope commented on docs/include-cmd-network.rst
> +           network.http.max_open ≫ ‹seconds›
"seconds" looks like a copy+paste error

2017-03-25 22:08 UTC, pyroscope commented on docs/include-cmd-items.rst
>      d.resume
Add a new **TODO** (or move the existing one) if commands are not related to your insertion.

2017-03-25 22:08 UTC, pyroscope commented on docs/include-cmd-items.rst
> +
"info hash"

2017-03-25 22:09 UTC, pyroscope commented
:+1: Great! If more people invest some time, this might actually get complete.

2017-03-25 23:36 UTC, kannibalox commented
I've updated the PR, I'll keep it them limited to one file in the future too.

2017-03-26 01:12 UTC, pyroscope approved these changes

2017-03-26 01:13 UTC, merged