More item commands
rtorrent-community/rtorrent-docs pull request #2
Opened 2017-04-16 01:19 UTC by kannibalox

2017-04-19 17:34 UTC, pyroscope requested changes
some fixes. nice cross-links. ;)

2017-04-19 17:34 UTC, pyroscope commented on docs/include-cmd-items.rst
> +            d.custom1 = string ‹key› ≫ string ‹value›
wrong signature

2017-04-19 17:34 UTC, pyroscope commented on docs/include-cmd-items.rst
> +        Set and return custom values with arbitary keys. Note that ``d.custom1=`` is *not* the same as ``d.custom=1`` or ``d.custom=custom1``, and can only be accessed by its assigned commands.
^^^ arbitary
vvv doens't

2017-04-19 17:34 UTC, pyroscope commented on docs/include-cmd-items.rst
> +        Used to store messages relating to the item, such as errors in communicating with the traker or a hash check failure.
traker

2017-04-19 17:34 UTC, pyroscope commented on docs/include-cmd-items.rst
> +        Returns the ratio of the torrent. This is the amount of uploaded data divided by the completed bytes in the items.
needs to mention the scale (×1000).

2017-04-19 17:34 UTC, pyroscope commented on docs/include-cmd-items.rst
> +        Skipped pieces are ones that are recieved from a peer, but aren't needed and are thus ignored. This
recieved

2017-04-19 17:34 UTC, pyroscope commented on docs/include-cmd-items.rst
> +            d.uploads_min = ‹hash› ≫ value ‹max›
s/max/min/

2017-04-20 02:32 UTC, kannibalox commented
Ugh I need to figure out a good way to spell check, too many false positives on the command names at the moment.

2017-04-30 20:06 UTC, merged